name: Publish to scoop bucket
on:
  push:
  workflow_dispatch:
    inputs:
      VERSION:
        description: "The release version of kbcli"
        type: string
        required: true
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: apecloud/scoop-bucket
          path: scoop
          token: ${{ env.GITHUB_TOKEN }}
      - name: cd the scoop
        run: |
          cd scoop
      - name: run autoupdate
        uses: foosel/scoop-checkver-action@main
        with: bucket
      - name: auto update scoop-bucket
        run: | 
          git commit -m "Updated apps"
          git push
#          cd scoop/bucket
#          cp scoop/bucket scoop/bucket/old
#          cat scoop/bucket/kbcli.json | jq '.version="${{ inputs.VERSION }}"'